name: crystal spec

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version: 12.16.0
      - uses: actions/checkout@v1
      - name: Install NPM dependencies
        run: npm --version
      # - name: Run tests
      # run: crystal spec
